// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Krados/idpool/internal/conf"
	"github.com/Krados/idpool/internal/controller"
	"github.com/Krados/idpool/internal/data"
	"github.com/Krados/idpool/internal/server"
	"github.com/Krados/idpool/internal/service/idpool"
	"github.com/gin-gonic/gin"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func initApp(cfg *conf.Config, sugar *zap.SugaredLogger) (*gin.Engine, error) {
	db := data.NewMySQL(cfg)
	idPoolRepo := idpool.NewMysqlIDRepo(db)
	idPoolServ := idpool.NewIDPoolServ(idPoolRepo)
	idController := controller.NewIDController(sugar, idPoolServ)
	engine := server.NewHTTPServer(idController)
	return engine, nil
}
